#!/bin/bash
#SBATCH --job-name=example_sbatch
#SBATCH --output=runjob.out
#SBATCH --error=runjob.err
#SBATCH --time=10:00:00
#SBATCH --partition=mfj
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=28
#SBATCH --mem-per-cpu=2000
#SBATCH --mail-type=END,FAIL      
#SBATCH --mail-user=skhani@uchicago.edu

ulimit -s unlimited

module unload intel intelmpi
module unload netcdf
module load intelmpi/5.1+intel-16.0
module load netcdf/4.4.1+intel-16.0
module load netcdf-fortran/4.4.4+intel-16.0

cd /scratch/midway2/skhani/Neverland/NL_1deg
mpirun -n 56 ../build/Midway-intel/ocean_only/repro/MOM6 > std.out


